### PR TITLE
Add Traditional Chinese Translation and Fix bug

### PR DESCRIPTION
**Pull request by Qingyu510**
Fix the error on line 1490 and 1650
Add Traditional Chinese Translation
No bugs appeared after testing

### CODE REVIEW

**Comment by Creckeryop** [comment]
Thank you, i will resolve all things later

**Comment by Qingyu510** [comment]
I added a new entry for translation

**Comment by Creckeryop** [comment]
Thank you so much, helping me with NOBORU!
I also don't know if you end making your changes, if you will make any other changes, please refork project!
If you think that this translation is over, notify me, i will release new version!

**Comment by Qingyu510** [comment]
Okay, I am adding and modifying entries to achieve the desired effect.
This time I will confirm that there are no problems before submitting.

**Pull request merged**
