### PR TITLE
Fix description bug

### PR DESCRIPTION
**Pull request by Qingyu510**

### CODE REVIEW

**Comment by Qingyu510** [comment]
In the imported comics, open "Open in browser", an error will be reported.  It is recommended to remove the "Open in browser" option for importing comics

**Comment by Creckeryop** [comment]
Thank you again, i think your change makes the RAW more logical now

**Comment by Creckeryop** [comment]
I don't know why but 

> In the imported comics, open "Open in browser", an error will be reported. It is recommended to remove the "Open in browser" option for importing comics

Open in browser doesn't work sometimes, i really don't know what to do, maybe delete this thing?

**Comment by Qingyu510** [comment]
> 我不知道为什么
> 
> > 在导入的漫画中，打开“在浏览器中打开”，将报告错误。建议删除用于导入漫画的“在浏览器中打开”选项
> 
> 有时无法在浏览器中打开，我真的不知道该怎么办，也许删除此东西？

It is recommended to keep only the "Open in browser" function of online comics

**Comment by Creckeryop** [comment]
done

**Comment by Qingyu510** [comment]
@Creckeryop 
When there is no cached comic chapter, open "Advanced Chapter Delete".  Select "delete" and "read" options will report an error

**Comment by Creckeryop** [comment]
I will

**Comment by Creckeryop** [comment]
I really didn't tested enough my app

**Pull request merged**
