### PR TITLE
Update Simplified Chinese and Traditional Chinese Translation

### PR DESCRIPTION
**Pull request by Qingyu510**
Update Simplified Chinese and Traditional Chinese

### CODE REVIEW

**Comment by Qingyu510** [comment]
Please add a blank prompt in "IMPORT" and "Advanced chapters deletion"

**Comment by Creckeryop** [comment]
Please don't touch other languages, it will be better leave it in English, than translated trough translator(

**Comment by Qingyu510** [comment]
Ok, I will restore PortugueseBR now
@Creckeryop

**Comment by Creckeryop** [comment]
Thank you!

**Comment by Qingyu510** [comment]
Portuguese BR has been restored
@Creckeryop

**Comment by Creckeryop** [comment]
> Please add a blank prompt in "IMPORT" and "Advanced chapters deletion"
> 
> 
> 

I don't want to distract translators, it's my fault that new version won't have these blank things.

**Comment by Creckeryop** [comment]
Thank you very much!

**Pull request merged**
