### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by Qingyu510**
Update Simplified Chinese and Traditional Chinese translation

### CODE REVIEW

**Comment by Qingyu510** [comment]
The description (Japanese or Chinese) in parentheses after RAW is wrong.
RAW refers to unprocessed comics in terms of comics, mostly untranslated comics.

I found that an error occurred when I opened the "Advanced Chapter Delete"

**Comment by Creckeryop** [comment]
Thank you for translation, i will fix that issue

**Comment by Creckeryop** [comment]
Issue was connected to description update. Thank you for report!

**Comment by Qingyu510** [comment]
@Creckeryop 
When there is no cached comic chapter, open "Advanced Chapter Delete".  Select "delete" and "read" options will report an error

**Pull request merged**
