### PR TITLE
Japanese translation

### PR DESCRIPTION
**Pull request by kuragehimekurara1**
Japanese translation is complete. Please update.

### CODE REVIEW

**Comment by Creckeryop** [comment]
Very big thanks working on Japanese Noboru translation. Very Happy to see Japanese Noboru interface.

Here's some problems in the translation.

NO_LIBRARY_MANGA is a little long

漫画/コミックを追加するには、[カタログ]メニューで漫画やコミックを見つけて、[ライブラリに追加]を押します。

Can you place '\n' symbol somewhere in this text ('\n' symbol is line break symbol)


DOWNLOAD = "ダウンロード中の漫画",
Also this string is little long can you translate download tab somehow else please?

**Comment by Creckeryop** [comment]
Here's Noboru.vpk with Japanese language if you want to see your translation by yourself on PSVita

https://drive.google.com/file/d/1PhT2m2jjK1wok7WgD_4dUIHcdjaxEzXO/view?usp=sharing

**Comment by kuragehimekurara1** [comment]
Excuse me.  Immediately fix the translation in question

**Comment by kuragehimekurara1** [comment]
Fixed the translation in question.
How about this?

**Comment by Creckeryop** [comment]
Thank you!
Now it nice fits

**Pull request merged**
