### PR TITLE
swip with stick

### PR DESCRIPTION
**Pull request by M4iku**
[Feature Request] Automatically turn pages when using left analog stick #36

### CODE REVIEW

**Comment by Creckeryop** [comment]
You've just made a feature to turn pages by tilting stick?

**Comment by M4iku** [comment]
> You've just made a feature to turn pages by tilting stick?

Yes, only in vertical mode

**Comment by Creckeryop** [comment]
Sorry, i can't add this code in app, because "Horizontal" pages in Verical mode can't be viewed normally (stick tilt skips half of that pages). 
Also #36 is about neverending pages. It's not so possible for my app because:
* My app aren't designed for that
* I can't see in future the size of images i will get (maybe it's pointless)

**Comment by M4iku** [comment]
> Sorry, i can't add this code in app, because "Horizontal" pages in Verical mode can't be viewed normally (stick tilt skips half of that pages).
> Also #36 is about neverending pages. It's not so possible for my app because:
> 
> * My app aren't designed for that
> * I can't see in future the size of images i will get (maybe it's pointless)

No problem! btw Great APP! thanks!

**Pull request closed without merging**
